#! /usr/bin/env python3

import os
import urllib.request
import re

with open('device-handlers.list') as depfile:
	for line in depfile.readlines():
		print (line)

		response = urllib.request.urlopen(line.strip())
		file_contents = response.read().decode('UTF-8')
		namespace = re.search("namespace: \"(.*?)\"", file_contents).group(1)
		component_name = re.search("name: \"(.*?)\"", file_contents).group(1)
		component_name = component_name.lower().replace("(", "").replace(")", "").replace(" ", "-")


		out_path = os.path.join("devicetypes", namespace, component_name + ".src")
		if not os.path.exists(out_path):
			os.makedirs(out_path)

		filename = component_name + ".groovy"
		out_file = os.path.join(out_path, filename)
		print (out_file)
		with open(out_file, 'w') as outfile:
			outfile.write(file_contents)

print ("ALL OK\n")